/* DO NOT EDIT, file generated by nestjs-i18n */

import { Path } from "nestjs-i18n";
export type I18nTranslations = {
    "articleCategory": {
        "notFound": string;
        "create": string;
        "update": string;
    };
    "articleType": {
        "notFound": string;
        "create": string;
        "update": string;
    };
    "auth": {
        "username-already-used": string;
        "logout": {
            "success": string;
        };
    };
    "city": {
        "notFound": string;
    };
    "country": {
        "notFound": string;
    };
    "state": {
        "notFound": string;
    };
    "user": {
        "notFound": string;
    };
};
export type I18nPath = Path<I18nTranslations>;
